# Use official Python 3.11 image as base
FROM python:3.11-alpine

# Set working directory in the container
WORKDIR /app

# Copy requirements.txt to the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY src/ ./src

# Command to run the application
CMD ["python3", "src/main.py"]
